### ISSUE TITLE
Index Readme Is Too Blank

### ISSUE THREAD

**Issue by NorakGithub** [C0D1UM/technical-standard#15]
Add more content to the first page, only title look weird.

**Comment by powerdefy** [comment]
There must be a reason? @earthpyy

**Comment by NorakGithub** [comment]
I talk to Earth and he says it's okay krub. No problem to add more content.

**Comment by earthpyy** [comment]
> I talk to Earth and he says it's okay krub. No problem to add more content.

Yes krub, it'll appear after table of content in the first page krubb.
